data1 = '''
{
  "device_id": "DEVICE1234",
  "timestamp": 16256,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 15,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 16256,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 15,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 16256,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 15,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 16256,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3
}
'''

data2 = '''
{
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle."
}
'''

data3 = '''
{
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180
}
'''

data4 = '''
{
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180
}
'''

data5 = '''
{
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180
}
'''

data6 = '''
{
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180,
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "device_location": "Warehouse 23, Sector 7G, near the northwest corner.",
  "last_maintenance": "2024-06-01, technician ID 56789, all checks passed.",
  "network_status": "Connected to primary server. Signal strength optimal.",
  "notes": "Regular checkup completed. No irregularities found. Next scheduled maintenance: 2024-07-01.",
  "device_id": "DEVICE1234",
  "timestamp": 171784,
  "temperature": 24,
  "humidity": 45,
  "battery_level": 76,
  "signal_strength": 3,
  "latitude": 45,
  "longitude": 93,
  "pressure": 1012,
  "altitude": 150,
  "speed": 120,
  "acceleration": 5,
  "direction": 180,
  "status_message": "All systems operational. No issues detected during the last cycle.",
  "error_log": "No errors logged. System performance within expected parameters.",
  "update_info": "Firmware version 1.0.3 applied on 2024-05-12. No pending updates.",
  "direction": 180
}
'''