

class DataAccess(object):

    def create(self, pathname: str, data: str): ...

    def read(self, pathname: str) -> str: ...

    def update(self, pathname: str, data: str): ...

    def delete(self, pathname: str): ...
